apiVersion: v1
kind: Service
metadata:
  name: dw-auth-service
spec:
  selector:
    app: dw-auth-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30010
  type: NodePort