apiVersion: v1
kind: Service
metadata:
  name: dw-config-service
spec:
  selector:
    app: dw-config-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003
  type: NodePort