apiVersion: v1
kind: Secret
metadata:
  name: dw-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: Y2FzYTEyMzQ=
  POSTGRES_USER: Z2FuZ2E=
  AUTH_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXVnY3deMCZteWdudHQ1NmJyKCZiMHAmNHh3dzMkJXgpcEBjNzFhbG80K2Fsayhm
  JWT_SECRET_KEY: Z2FuZ2E=
  OPENPAYD_KEY: KCNlMiZvSkVSOA==
  POSTGRES_DB: cG9zdGdyZXM=
