kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dw-postgres-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: dw-postgres-pv