# Generated by Django 3.2.9 on 2023-01-07 02:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('NGA', 'Nigeria'), ('USA', 'United States of America')], help_text='ISO 3166-1 alpha-3 formatted country code', max_length=254)),
                ('currency', models.CharField(choices=[('NGN', 'Naria'), ('USD', 'US-Dollars')], help_text='ISO 4217 formatted country currency.', max_length=254)),
            ],
            options={
                'unique_together': {('country', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='SupportedCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('vat_percentage', models.DecimalField(decimal_places=2, help_text='Vat setting in percentage for all vatable items in the country.', max_digits=16)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Fee taken by the platform on each trip in percentage', max_digits=16)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_country', to='config.country')),
            ],
        ),
    ]
