apiVersion: v1
kind: Service
metadata:
  name: dw-wallet-service
spec:
  selector:
    app: dw-wallet-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30012
  type: NodePort