apiVersion: apps/v1
kind: Deployment
metadata: 
  name: celery-deploy
  labels:
    app: celery-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-deploy
  template:
    metadata:
      labels:
        app: celery-deploy
    spec:
      containers:
        - name: celery-deploy
          image: dw-auth-image:2.1
          command: ['celery', '-A', 'authService', 'worker', '-l', 'info']
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dw-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dw-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: dw-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: dw-auth-db-service
            - name: REDIS_HOST
              value: redis-service
            - name: DJANGO_SETTINGS_MODULE
              value: authService.settings.dev
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dw-secrets
                  key: AUTH_SECRET_KEY
            - name: REDIS_HOST
              value: redis
            


