# Generated by Django 3.2.9 on 2023-01-07 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for User bank accounts', primary_key=True, serialize=False)),
                ('account_details', models.JSONField(default=dict)),
                ('bank', models.CharField(help_text='Name of bank', max_length=50)),
                ('alias', models.CharField(blank=True, help_text='short name of bank', max_length=50, null=True)),
                ('account_number', models.CharField(default='', help_text='Bank account number', max_length=30)),
                ('is_default', models.BooleanField(default=False, help_text='Is this your default bank account?')),
                ('is_verified', models.BooleanField(default=False, help_text='Is this your bank account verified?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserWalletBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for user multiple virtual wallets', primary_key=True, serialize=False)),
                ('user', models.EmailField(max_length=256, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('withdrawable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserWalletPinModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for Wallet Transaction pin', primary_key=True, serialize=False)),
                ('user', models.EmailField(max_length=256, unique=True)),
                ('cypher_dict', models.JSONField(default=dict, help_text='User wallet cypher', max_length=100)),
                ('pin', models.CharField(default='', help_text='User wallet pin', max_length=100)),
                ('reset_code', models.CharField(default='', help_text='User wallet reset code', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for each user wallet', primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=1024, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Wallet balance', max_digits=16)),
                ('available', models.DecimalField(decimal_places=2, default=0, help_text='Wallet available balance', max_digits=16)),
                ('description', models.CharField(blank=True, help_text='Wallet description', max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('walletBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='wallet.userwalletbox')),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('walletBox', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='UserWalletWithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for Wallet withdrawals', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Withdrawal amount', max_digits=16)),
                ('is_accepted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Withdrawal description', max_length=250, null=True)),
                ('reference', models.CharField(blank=True, max_length=254, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Bank account funds are transferred to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.userbankaccount')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='wallet.wallets'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for each user wallet', primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=255)),
                ('wallet_available', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(default='Wallet Entry', max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('REFUND', 'Refund')], default='PENDING', max_length=50)),
                ('reference', models.CharField(max_length=1024, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='wallet.wallets')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
